mi_string = input()
print(mi_string)
print(type(mi_string))
print(len(mi_string))
print(mi_string)
print(mi_string.upper())
print(mi_string.lower())
print(mi_string.replace(" ","" ) )
print(mi_string[0])
print(mi_string[-1])